version: '3.8'

services:
  redis:
    image: redis:8.0.0
    container_name: redis
    ports:
      - "6379:6379"
    # command: >
    #   redis-server
    #   --search-workers 4
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local 